@URL_BASE=http://localhost:8080/person

### Obter uma pessoa pelo ID
GET {{URL_BASE}}/1

### Obter todas as pessoas
GET {{URL_BASE}}

### Criar uma pessoa
POST {{URL_BASE}}
Content-Type: application/json

{
    "name": "Juca",
    "email": "juca@gmail.com",
    "password": "123"
}

### Atualizar uma pessoa
PUT {{URL_BASE}}/1

{

}

### Deletar uma pessoa
DELETE {{URL_BASE}}/1